### ISSUE TITLE
global_param.f and common.h

### ISSUE THREAD

**Issue by yangf4** [SCOREC/phasta#1]
We have two files which store global variables: global_param.f and common.h. 
I am wondering if we have any criteria saying which variable goes into which? 
For example, if we introduce a new global variable about the layered mesh, where should it go?  

This issue is also used to test if everyone can receive a notification about this.

**Comment by shamse** [comment]
Depends on how you want to expose the new variable to where is gonna be used:
(1) put it in common.h and it will be available in any scope which common.h is included.
(2) add it in one of the modules (or new one) in global_param_m.f, then you can use 'implicit none' in the new scope, and expose your new variable via 'use module...'

**Comment by yangf4** [comment]
Thank you @shamse
