### ISSUE TITLE
thermal conductivity in penalty term (mu)

### ISSUE THREAD

**Issue by anirbanchandra1** [SCOREC/phasta#11]
Why is there a  '*100' for this term? 
Could you please look in to this? @yangf4  @shamse 
https://github.com/SCOREC/phasta/blob/master/phSolver/compressible/e3if_m.f#L155

**Comment by alexzhangyu** [comment]
I guess it was used temporarily for some test cases but forgot to fix afterward, I am not sure about that, maybe Ehsan could confirm that.
