### ISSUE TITLE
proper function name

### ISSUE THREAD

**Issue by yangf4** [SCOREC/phasta#5]
See these two functions:
https://github.com/SCOREC/phasta/blob/master/phSolver/compressible/e3if_m.f#L107
https://github.com/SCOREC/phasta/blob/master/phSolver/compressible/e3if_m.f#L153

We may need better names for these two functions.

**Comment by shamse** [comment]
done

**Comment by yangf4** [comment]
for reference: e770c3194f7d69396c4828d7e62398b8a80a61ca
