### ISSUE TITLE
brief comments of new added files for DG interface

### ISSUE THREAD

**Issue by yangf4** [SCOREC/phasta#6]
I would like to add brief explanation/doxygen of the new added files for DG interface. I have a list as below:
asidgif.f
asidgif_geom.f
block_m.f
e3_func_m.f
e3_param_m.f
e3if_diff_m.f
e3if_func_m.f
e3if_geom_m.f
e3if_lhs_m.f
e3if_m.f
e3if_param_m.f
e3if_setparam.f
e3if_vi_m.f
e3metric_m.f
eqn_state_m.f
if_global_m.f
if_velocity_m.f
ifbc_m.f
kappa_error.f
probe_m.f

I will work on this but any helper is welcome, especially @shamse .

**Comment by yangf4** [comment]
also includes:
asadj_m.f
genbkif.f
genint_m.f
genshp_m.f
gensavif.f
local_m.f

**Comment by yangf4** [comment]
Hi @shamse ,

I am wondering what does probe_m.f do?

**Comment by shamse** [comment]
probe_m.f was made to monitor conservation laws over the entire domain. It integrates conservative variables over the entire domain and prints the values. 

Can be activated by setting "Conservation Probe = Yes"

It may still need debugging. Be aware when using.

**Comment by yangf4** [comment]
commit: 44f992ff95a4bfb7716a6f52ec6b702e5a259059
