### ISSUE TITLE
in memory geombc not read correctly by phasta (or not generated correctly by phastaChef)

### ISSUE THREAD

**Issue by asroy** [SCOREC/phasta#9]
When using phastaChef generate geombc and restart file in memory, and running in-memory base phasta, the "material type boundary" array phasta retrieve from geombc is wrong.

However, this array is generated correctly in function core/phasta/phGeomBC.cc::writeBlocks, before it is written into in-memory geombc file

Also, when phastaChef and phasta are file-based, there is no such issue.

**Comment by yangf4** [comment]
fix is here:
https://github.com/SCOREC/phasta/commit/1a857ba55949aef62f95937463d0f3e6d7951ab3
